# Generated by Django 5.1.1 on 2024-11-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_question_question_context_alter_question_text"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="unique_correct_choice",
            ),
        ),
    ]
