# Generated by Django 4.2.16 on 2025-01-01 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickplayQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_1", models.CharField(max_length=200)),
                ("option_2", models.CharField(max_length=200)),
                ("option_3", models.CharField(max_length=200)),
                ("option_4", models.CharField(max_length=200)),
                ("correct_answer", models.CharField(max_length=200)),
                ("explanation", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("logical_reasoning", "Logical Reasoning"),
                            ("verbal_linguistic", "Verbal Linguistic"),
                            ("spatial_reasoning", "Spatial Reasoning"),
                            ("critical_thinking", "Critical Thinking"),
                        ],
                        default="reasoning",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QuickplayGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                ("lives_remaining", models.IntegerField(default=3)),
                ("is_completed", models.BooleanField(default=False)),
                ("time_limit", models.IntegerField(default=300)),
                (
                    "categories",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of selected categories",
                        max_length=255,
                    ),
                ),
                ("highest_speed_level", models.IntegerField(default=60)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="QuickplayAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField()),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickplay.quickplaygame",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickplay.quickplayquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["answered_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("date_achieved", models.DateTimeField(auto_now_add=True)),
                ("time_taken", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leaderboard Entries",
                "ordering": ["-score", "time_taken"],
            },
        ),
    ]
