# Generated by Django 4.2.16 on 2025-01-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickplay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=255)),
                ("wrong_answers", models.JSONField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("logical_reasoning", "Logical Reasoning"),
                            ("verbal_linguistic", "Verbal Linguistic"),
                            ("spatial_reasoning", "Spatial Reasoning"),
                            ("critical_thinking", "Critical Thinking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("times_used", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
