# Generated by Django 4.2.16 on 2025-01-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickplay", "0002_aiquestion"),
    ]

    operations = []
