# Generated by Django 4.2.16 on 2024-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickplay", "0002_quickplaygame_categories_quickplayquestion_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickplayquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("logical_reasoning", "Logical Reasoning"),
                    ("verbal_linguistic", "Verbal Linguistic"),
                    ("spatial_reasoning", "Spatial Reasoning"),
                    ("critical_thinking", "Critical Thinking"),
                ],
                default="reasoning",
                max_length=20,
            ),
        ),
    ]
