# Generated by Django 4.2.16 on 2025-01-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickplay", "0003_auto_20250120_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("logical_reasoning", "Logical Reasoning"),
                    ("quantitative_reasoning", "Quantitative Reasoning"),
                    ("linguistic_reasoning", "Linguistic Reasoning"),
                    ("spatial_reasoning", "Spatial Reasoning"),
                ],
                max_length=25,
            ),
        ),
    ]
